services:
  gitlab:
    container_name: gitlab
    hostname: gitlab.home
    image: gitlab/gitlab-ee:latest
    restart: unless-stopped
    networks:
      - dockernet
    volumes:
      - ./config:/etc/gitlab
      - ./data:/var/opt/gitlab
      - ./logs:/var/log/gitlab
    environment:
      TZ: Europe/Berlin
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://gitlab.home.schndr.cloud"
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        letsencrypt['enable'] = false
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = "none"
        gitlab_rails['smtp_address'] = "postfix"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_user_name'] = "${SMTP_USERNAME}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['gitlab_email_from'] = "${EMAIL_FROM}"
        gitlab_rails['gitlab_email_display_name'] = "GitLab"
        puma['worker_processes'] = 2
        sidekiq['concurrency'] = 5
        gitlab_rails['mirror_max_delay'] = 86400
        prometheus_monitoring['enable'] = false
        gitlab_kas['enable'] = false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.entryPoints=websecure"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.home.schndr.cloud`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
networks:
  dockernet:
    external: true
