services:
  immich:
    container_name: immich
    hostname: immich.home
    image: ghcr.io/immich-app/immich-server:latest
    restart: unless-stopped
    networks:
      - dockernet
    environment:
      TZ: Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.entryPoints=websecure"
      - "traefik.http.routers.immich.rule=Host(`immich.home.schndr.cloud`)"
      - "traefik.http.services.immich.loadbalancer.server.port="
networks:
  dockernet:
    external: true
