---

- Infrastructure:
    - UniFi:
        href: https://unifi.home.schndr.cloud
        icon: unifi
        description: Network Management
        ping: 10.10.10.1
    - Proxmox VE:
        href: https://proxmox.home.schndr.cloud
        icon: proxmox
        description: VMs
        ping: 10.10.10.10
    - Proxmox Backup Server:
        href: https://pbs.home.schndr.cloud
        icon: proxmox
        description: Backup VMs
        ping: 10.10.10.11
    - TrueNAS (Monty):
        href: https://monty.home.schndr.cloud
        icon: truenas
        description: NAS
        ping: 10.10.10.20
    - TrueNAS (Aria):
        href: https://aria.home.schndr.cloud
        icon: truenas
        description: Backup NAS
        ping: 100.118.182.87
    - GL.iNet Comet:
        href: https://kvm.home.schndr.cloud
        icon: glinet
        description: KVM
        ping: 10.10.10.13
- Administration:
    - Pi-Hole:
        href: https://pihole.home.schndr.cloud/admin
        icon: pi-hole
        description: Ad Blocking & DNS
        server: docker
        container: pi-hole
    - Traefik:
        href: https://traefik.home.schndr.cloud
        icon: traefik
        description: Reverse Proxy
        server: docker
        container: traefik
    - Portainer:
        href: https://portainer.home.schndr.cloud
        icon: portainer
        description: Container Management
        server: docker
        container: portainer
    - VS Code:
        href: https://vscode.home.schndr.cloud
        icon: vscode
        description: Code Editor
        server: docker
        container: vscode
- Smart Home:
    - Home Assistant:
        href: https://homeassistant.home.schndr.cloud
        icon: home-assistant
        description: Home Automation
        server: docker
        container: home-assistant
    - Zigbee2MQTT:
        href: https://zigbee2mqtt.home.schndr.cloud
        icon: zigbee2mqtt
        description: Zigbee to MQTT Bridge
        server: docker
        container: zigbee2mqtt
    - SLZB-06M:
        href: https://slzb.home.schndr.cloud
        icon: si-zigbee-#EB0443
        description: Zigbee Coordinator
        ping: 10.10.80.2
    - Shelly Pro 3EM:
        href: http://10.10.80.3
        icon: shelly
        description: Power Consumption Meter
        ping: 10.10.80.3
    - Shelly 2PM Gen4 (Schlafzimmer):
        href: http://10.10.80.20
        icon: shelly
        description: Relais
        ping: 10.10.80.20
    # - LED-Matrix:
    #     href: http://10.10.80.80
    #     icon: wled
    #     description: WLED
    #     ping: 10.10.80.80
- Services:
    - Crafty:
        href: https://crafty.home.schndr.cloud
        icon: crafty-controller
        description: Minecraft Servers
        ping: 10.10.10.210
    - Docmost:
        href: https://docmost.home.schndr.cloud
        icon: docmost
        description: Wiki and Documentation
        server: docker
        container: docmost
    - GitLab:
        href: https://gitlab.home.schndr.cloud
        icon: gitlab
        description: DevOps Platform
        server: docker
        container: gitlab
    - Grafana:
        href: https://grafana.home.schndr.cloud
        icon: grafana
        description: Data Visualization
        server: docker
        container: grafana
    # - Immich:
    #     href: https://immich.home.schndr.cloud
    #     icon: immich
    #     description: Photo Manager
    #     server: docker
    #     container: immich
    - Jellyfin:
        href: https://jellyfin.home.schndr.cloud
        icon: jellyfin
        description: Media Streaming
        server: docker
        container: jellyfin
    - Linkding:
        href: https://linkding.home.schndr.cloud
        icon: linkding
        description: Bookmark Manager
        server: docker
        container: linkding
    - MeTube:
        href: https://metube.home.schndr.cloud
        icon: metube
        description: Web GUI for yt-dlp
        server: docker
        container: metube
    - n8n:
        href: https://n8n.home.schndr.cloud
        icon: n8n
        description: Workflow Automation
        server: docker
        container: n8n
    - Uptime Kuma:
        href: https://uptimekuma.home.schndr.cloud
        icon: uptime-kuma
        description: Uptime Monitoring
        server: docker
        container: uptime-kuma
    - Vaultwarden:
        href: https://vaultwarden.home.schndr.cloud
        icon: bitwarden
        description: Password Manager
        server: docker
        container: vaultwarden
