---

title: Homelab
theme: dark
color: gray
headerStyle: clean
statusStyle: dot
disableCollapse: true
hideVersion: true
layout:
  - Infrastructure:
      style: column
  - Administration:
      style: column
  - Smart Home:
      style: column
  - Services:
      style: row
      columns: 5
  - Tools:
      style: row
      columns: 5
